
export interface Resume {
  name: string;
  email: string;
  year: string;
  major: string[];
  college: string[];
  visa: string;
  link: string;
}

export const resumes: Resume[] = [
  {
    name: 'Afsha Rehman ',
    email: 'rehma068@umn.edu',
    year: 'Senior',
    major: ["Chemical Engineering"],
    college: ["CSE"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1KR5JfWzCR231zFowvYEFYIkeoP3nY-gq/preview',
  },
  {
    name: 'Annalise Xiao',
    email: 'xiao0332@umn.edu',
    year: 'Junior',
    major: ["Data Science"],
    college: ["CSE"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1mFSg6BS5OlirMBfsMEM5mVAjEKFMK5mQ/preview',
  },
  {
    name: 'Ansh Patel',
    email: 'pate1011@umn.edu',
    year: 'Junior',
    major: ["Computer Science"],
    college: ["CSE"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1Aevql40Alvtvp7yemy34eKAuCTe7HTKu/preview',
  },
  {
    name: 'Benjamin Sebastian',
    email: 'sebas063@umn.edu',
    year: 'Senior',
    major: ["Computer Science"],
    college: ["CSE"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1L0MCMYEIcqM9jRTBTcuGKmWrNe6RNebW/preview',
  },
  {
    name: 'Betty Huynh',
    email: 'huynh498@umn.edu',
    year: 'Senior',
    major: ["Industrial and Systems Engineering"],
    college: ["CSE"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1B8gzMAUE8BCuk7cGrFmDUNdHFPrkcyCo/preview',
  },
  {
    name: 'Eunice Tong',
    email: 'tong0163@umn.edu',
    year: 'Junior',
    major: ["Chemistry"],
    college: ["CSE"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1qeGKwzLj_wPPmpsy8edvxrcFFjGuTWDQ/preview',
  },
  {
    name: 'Harini Kuchibhotla',
    email: 'kuchi027@umn.edu',
    year: 'Sophomore',
    major: ["Computer Science","Data Science"],
    college: ["CSE"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1VY3kJhf7BlcRSiUDAqDazWXvdxuNWs1G/preview',
  },
  {
    name: 'Henry Le',
    email: 'le000379@umn.edu',
    year: 'Junior',
    major: ["Computer Science"],
    college: ["CSE"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1uy5picyOXA-fijUGs5sJrWhzeVNlzL-J/preview',
  },
  {
    name: 'Hillary Vo',
    email: 'vo000074@umn.edu',
    year: 'Senior',
    major: ["Mathematics"],
    college: ["CSE"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1NTfMfzv8cYPLyF5bWJNtuflGEUaBsBIm/preview',
  },
  {
    name: 'Jiaxi Tang',
    email: 'tang0773@umn.edu',
    year: 'Junior',
    major: ["Computer Science","Graphic Design"],
    college: ["CSE"," CDES"],
    visa: 'Yes',
    link: 'https://drive.google.com/file/d/1UErZnr5yfm9vZ4-4fTzc3Q44HLdBKDwh/preview',
  },
  {
    name: 'Joseph Hoang',
    email: 'hoang340@umn.edu',
    year: 'Senior',
    major: ["Aerospace Engineering","Mathematics"],
    college: ["CSE"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1jPH2J0vHQDEVALfVLzhdSAJxBGF9BoX7/preview',
  },
  {
    name: 'Julie Bondy',
    email: 'bondy031@umn.edu',
    year: 'Graduate',
    major: ["Microbial Engineering"],
    college: ["CBS"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/11zA1Z_N4QA3-cC02ENWiqleU98xh6-7W/preview',
  },
  {
    name: 'Kevin Benny ',
    email: 'kevin005@umn.edu',
    year: 'Graduate',
    major: ["Data Science"],
    college: ["CSE"],
    visa: 'Yes',
    link: 'https://drive.google.com/file/d/15hjECzLBPSX85zRCDsh8HLHz-R8Au2BE/preview',
  },
  {
    name: 'Kriti Kamath',
    email: 'kamat095@umn.edu',
    year: 'Senior',
    major: ["Mathematics"],
    college: ["CSE"],
    visa: 'Yes',
    link: 'https://drive.google.com/file/d/1_Y6k3wgRLQUeTsLe_-sNDePeNt0uLqDC/preview',
  },
  {
    name: 'Kyle Gordon ',
    email: 'gordo892@umn.edu',
    year: 'Freshman',
    major: ["Electrical Engineering"],
    college: ["CSE"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1SXlBI2-ELam49CriH_FYknUdxBH9pOPM/preview',
  },
  {
    name: 'Lahari Hosur',
    email: 'hosur004@umn.edu',
    year: 'Sophomore',
    major: ["Aerospace Engineering"],
    college: ["CSE"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1vW1LNYpcUOm3Oiwa_OXhURNV4njSJEiX/preview',
  },
  {
    name: 'Matthew Xue',
    email: 'xue00126@umn.edu',
    year: 'Junior',
    major: ["Computer Science"],
    college: ["CSE"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1sjhJXSuiJHzseHGKvI01JTAgP-rrjonP/preview',
  },
  {
    name: 'Nilay Singh Mer',
    email: 'mer00002@umn.edu',
    year: 'Sophomore',
    major: ["Management Information Systems","Finance"],
    college: ["CSOM"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1bkGKi3goX8viwVh_EQ9_fJtVNtWn2aOn/preview',
  },
  {
    name: 'Pearl Jain',
    email: 'jain0377@umn.edu',
    year: 'Sophomore',
    major: ["Computer Science","Data Science"],
    college: ["CSE"],
    visa: 'Yes',
    link: 'https://drive.google.com/file/d/1FgY5mTnVH9dFtfa72_VIAToiQpeo1GFD/preview',
  },
  {
    name: 'Riya Bharti',
    email: 'bhart022@umn.edu',
    year: 'Junior',
    major: ["Computer Science","Mathematics"],
    college: ["CSE"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1MI6TyIkXsaT6mjKAK248MjZjs9LlLcxB/preview',
  },
  {
    name: 'Sai Rishi Yerramorusu',
    email: 'yerra034@umn.edu',
    year: 'Sophomore',
    major: ["Computer science","Data Science"],
    college: ["CSE"],
    visa: 'Yes',
    link: 'https://drive.google.com/file/d/1wby791JrGmDMi9El3CfbqaelClKe5L0S/preview',
  },
  {
    name: 'Saloni Shah',
    email: 'shah0925@umn.edu',
    year: 'Freshman',
    major: ["Computer Engineering"],
    college: ["CSE"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1UXiRvatH7aXEjp3FIvUKGVcVC5Mj87fO/preview',
  },
  {
    name: 'Shannon Vue',
    email: 'vue00201@umn.edu',
    year: 'Junior',
    major: ["Neuroscience"],
    college: ["CBS"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1SrceeIT84xMyWYVOgkhDvsLMdcmSNXe-/preview',
  },
  {
    name: 'Shreya Srivastava ',
    email: 'sriva263@umn.edu',
    year: 'Junior',
    major: ["Computer Science"],
    college: ["CSE"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1J-GDBT4ssnqjSiweDd1Gk-4kbFnaydAl/preview',
  },
  {
    name: 'Tommy Le',
    email: 'le000397@umn.edu',
    year: 'Junior',
    major: ["Computer Science"],
    college: ["CSE"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1jJFBem9LKq9FelWN0Tk5pqdtz8Qx6shF/preview',
  },
  {
    name: 'Whitney Le',
    email: 'le000329@umn.edu',
    year: 'Senior',
    major: ["Management Information Systems","Neuroscience","Genetics"],
    college: ["CBS"," CSOM"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1QDEuUeUWDajP4feH_0dEydY3E4kwpA92/preview',
  },
];